#include "wifiscan.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "screen.h"

void read_data(void){
	FILE *fp;
	WIFI_INFO wf, wf_list[100]; //list for network
	int i=0, c; //line counter
	char line[200];
	//read data from scan.txt file is generated by iwlist
	if((fp = fopen("scan.txt", "r")) == NULL){
		printf("Cannot open file %s\n", "scan.txt");
		return;
	} 
	while(fgets(line,200,fp)!=NULL){
#ifdef DEBUG
		// printf("Line read;%s",line);
#endif 
		remove_spaces(line);
		if(strncmp(line,"Cell",4) == 0){
			c=0; //reset line counter to 0
			get_MAC(line, wf.MAC); // get MAC in first line
		}
		else{
			c++; // line counter increments
			if(c==1){ //second line contains frequency and channel
				wf.frequency = get_freq(line);
				wf.channel = get_channel(line);
			} 
			if(c==2){ //third line contains signal level
				wf.slevel = get_slevel(line);
			}
		  	if(c==3){ //get name of network and add to list
				get_essid(line, wf.essid);
				wf_list[i++] = wf;
			}
		} 
	}
	fclose(fp);
	displayNetworks(wf_list, i);
}	

void displayNetworks(WIFI_INFO wlist[], int c){
	int i;
	clearScreen();
#ifndef DEBUG
	gotoXY(1,1); 
	printf("%d Networks", c); 
	// display channel numbers
	for(i=0; i<13; i++){
		gotoXY(36, 13+i*5); printf("%d", i+1);
	}
#endif
	for(i=0; i<c; i++){
#ifdef DEBUG
		printf("MAC: %s\n",wlist[i].MAC);
		printf("Channel: %d\n",wlist[i].channel);
		printf("Frequency: %.3f GHz\n",wlist[i].frequency);
		printf("Signal level: %.0f dBm\n", wlist[i].slevel);
		printf("ESSID: %s\n\n", wlist[i].essid); 
#else 
		display_UI(wlist[i], i);
#endif
	}
}

//remove spaces in front of each line
void remove_spaces(char s[]){
	int i, len = strlen(s);
	for(i=0;i<len;i++){
		if(s[i] != ' ' && s[i] !='\t' && s[i] !='\n') break;
	}
	strcpy(s,&s[i]);
	
}

//get MAC of a cell
void get_MAC(char line[],char mac[]){
	int i; //19 characters of cell and address:
	strncpy(mac,&line[19],17);
}

//return frequency of one network
double get_freq(char line[]){
	double freq; 
	char *find;
	find = strstr (line,"Frequency");
	freq = atof(strncpy(line, find+10,5));
	 //freq = 2.413 for example, 10 is number of word we do not care
	return freq; 
}

//return channel of one network
int get_channel(char line[]){
	int i, j, len = strlen(line);
	char temp[10];	
	
	for(i=0; i<len; i++) 	// find ')'
		if(line[i]==')') break;
	
	for(j=i; j>=0; j--)		// find the white space in front of it.
		if(line[j]==' ') break;
	
	strncpy(temp, &line[j+1], i-j-1);
	return atoi(temp);
}

//return signal level of one network
double get_slevel(char line[]){
	char *find;
	find = strstr(line,"Signal level");
	double s_level = atof(strncpy(line,find+13,3));
	return s_level;
}

//return name of one network
void get_essid(char line[], char essid[]){
	strcpy(essid,&line[7]); //Remove 7 characters: ESSID: in scan.txt
	essid[strlen(essid)-2] = '\0'; //Remove the last "
}

//display one network for user
void display_UI(WIFI_INFO w, int c){
	int row, col;
	setFGcolor(RED + c%7);	
	row = (-30-w.slevel)/2 + 1;
	col = (w.channel-1)*5+13;
	drawRect(row, col-11, 35-row, 22);
	gotoXY(row, col-strlen(w.essid)/2);
	printf("%-s", w.essid);
	resetColors();
}
